language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r: devel
      env: CXX1X="g++ -std=c++0x -g -O2 -fPIC"
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: hunspell
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      latex: false
      disable_homebrew: true

addons:
  apt:
    packages:
      - libhunspell-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - if [[ "${CXX1X}" ]]; then mkdir ~/.R && echo "CXX1X=$CXX1X" > ~/.R/Makevars; fi

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
