language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      brew_packages: hunspell
    - os: osx
      osx_image: xcode8
      disable_homebrew: true

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
